import { Helmet } from "react-helmet-async";

export default function Disclaimer() {
  return (
    <>
      <Helmet>
        <title>Disclaimer - MindRecap</title>
      </Helmet>
      <div className="max-w-3xl mx-auto prose prose-slate py-12">
        <h1>Disclaimer</h1>
        <p>Last updated: March 2024</p>
        <p>
          The information provided by MindRecap ("we", "us", or "our") on mindrecap.app is for general informational purposes only.
        </p>
        <h2>1. AI Accuracy</h2>
        <p>
          MindRecap uses artificial intelligence to generate summaries. While we strive for accuracy, AI can sometimes misinterpret context or omit important details. Users should always verify critical information against the original source.
        </p>
        <h2>2. External Links</h2>
        <p>
          Our site contains links to external websites (affiliate links). We are not responsible for the content or privacy practices of these sites. We may receive a commission if you purchase a product through one of our affiliate links.
        </p>
        <h2>3. No Professional Advice</h2>
        <p>
          The summaries generated by MindRecap do not constitute professional, legal, or financial advice. We are not liable for any decisions made based on the summaries provided by our tool.
        </p>
      </div>
    </>
  );
}
