import { Helmet } from "react-helmet-async";

export default function PrivacyPolicy() {
  return (
    <>
      <Helmet>
        <title>Privacy Policy - MindRecap</title>
      </Helmet>
      <div className="max-w-3xl mx-auto prose prose-slate py-12">
        <h1>Privacy Policy</h1>
        <p>Last updated: March 2024</p>
        <p>
          At MindRecap, we take your privacy seriously. This policy explains how we handle your data.
        </p>
        <h2>1. Data Collection</h2>
        <p>
          MindRecap is a stateless application. We do not store the text you paste into our summarizer or the summaries generated by our AI. All processing happens in real-time and data is discarded immediately after the response is sent.
        </p>
        <h2>2. Cookies</h2>
        <p>
          We use essential cookies to maintain your session and improve your experience. We also use third-party services like Google AdSense which may use cookies to serve personalized ads.
        </p>
        <h2>3. Third-Party Services</h2>
        <p>
          We use Google Gemini API for summarization and YouTube Transcript API for video processing. These services have their own privacy policies which you should review.
        </p>
        <h2>4. Contact Us</h2>
        <p>
          If you have any questions about this policy, please contact us at support@mindrecap.app.
        </p>
      </div>
    </>
  );
}
