import { useState } from 'react';
import { Search, CheckCircle2, AlertTriangle } from 'lucide-react';
import { ToolWrapper } from './ToolWrapper';
import { motion } from 'motion/react';

export function AIDetector({ isPro }: { isPro: boolean }) {
  const [text, setText] = useState('');
  const [isProcessing, setIsProcessing] = useState(false);
  const [result, setResult] = useState<{ aiScore: number, humanScore: number } | null>(null);

  const handleDetect = async () => {
    setIsProcessing(true);
    try {
      const res = await fetch('/api/detect', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ text })
      });
      const data = await res.json();
      if (res.ok) {
        setResult(data);
      } else {
        alert(data.error || 'Failed to analyze text.');
      }
    } catch (error) {
      console.error(error);
      alert('Network error occurred.');
    } finally {
      setIsProcessing(false);
    }
  };

  return (
    <ToolWrapper
      title="AI Detector"
      description="Detect content from GPT-4, Claude, and Gemini."
      isPro={isPro}
      value={text}
      onChange={(val) => { setText(val); if(result) setResult(null); }}
      onAction={handleDetect}
      actionLabel="Detect AI Content"
      actionIcon={<Search className="w-5 h-5" />}
      isProcessing={isProcessing}
    >
      {result && (
        <div className="flex flex-col h-full">
          <div className="p-4 border-b border-slate-100 bg-slate-50/50 flex items-center justify-between">
            <h3 className="font-semibold text-slate-800">Detection Results</h3>
            <button onClick={() => setResult(null)} className="text-xs text-blue-600 hover:underline font-medium">
              New Scan
            </button>
          </div>
          
          <div className="flex-1 p-8 flex flex-col items-center justify-center">
            <div className="relative w-48 h-48 mb-8">
              <svg viewBox="0 0 100 50" className="w-full h-full overflow-visible">
                <path 
                  d="M 10 50 A 40 40 0 0 1 90 50" 
                  fill="none" 
                  stroke="#e2e8f0" 
                  strokeWidth="12" 
                  strokeLinecap="round" 
                />
                <motion.path 
                  d="M 10 50 A 40 40 0 0 1 90 50" 
                  fill="none" 
                  stroke={result.aiScore > 50 ? "#ef4444" : "#10b981"} 
                  strokeWidth="12" 
                  strokeLinecap="round"
                  initial={{ pathLength: 0 }}
                  animate={{ pathLength: result.aiScore / 100 }}
                  transition={{ duration: 1, ease: "easeOut" }}
                  style={{ strokeDasharray: "125.6", strokeDashoffset: "125.6" }}
                />
              </svg>
              <div className="absolute bottom-0 left-1/2 -translate-x-1/2 text-center">
                <div className="text-4xl font-bold text-slate-900">{result.aiScore}%</div>
                <div className="text-sm font-medium text-slate-500 uppercase tracking-wider">AI Generated</div>
              </div>
            </div>

            <div className="w-full max-w-sm space-y-4">
              <div className="flex items-center justify-between p-4 rounded-xl bg-slate-50 border border-slate-100">
                <div className="flex items-center gap-3">
                  <div className="w-2 h-2 rounded-full bg-emerald-500" />
                  <span className="font-medium text-slate-700">Human</span>
                </div>
                <span className="font-bold text-slate-900">{result.humanScore}%</span>
              </div>
              <div className="flex items-center justify-between p-4 rounded-xl bg-slate-50 border border-slate-100">
                <div className="flex items-center gap-3">
                  <div className="w-2 h-2 rounded-full bg-red-500" />
                  <span className="font-medium text-slate-700">AI</span>
                </div>
                <span className="font-bold text-slate-900">{result.aiScore}%</span>
              </div>
            </div>

            <div className={`mt-8 flex items-start gap-3 p-4 rounded-xl text-sm ${result.aiScore > 50 ? 'bg-red-50 text-red-800' : 'bg-emerald-50 text-emerald-800'}`}>
              {result.aiScore > 50 ? (
                <AlertTriangle className="w-5 h-5 shrink-0 mt-0.5" />
              ) : (
                <CheckCircle2 className="w-5 h-5 shrink-0 mt-0.5" />
              )}
              <p>
                {result.aiScore > 50 
                  ? "This text is highly likely to be generated by an AI model. Consider using our AI Humanizer to make it more natural."
                  : "This text appears to be written by a human. It exhibits natural variations in perplexity and burstiness."}
              </p>
            </div>
          </div>
        </div>
      )}
    </ToolWrapper>
  );
}
