import { jsPDF } from "jspdf";
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from "docx";
import { saveAs } from "file-saver";
import { MeetingAnalysis } from "../types";

export const generatePDF = (data: MeetingAnalysis) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - (margin * 2);
  let yPos = 20;

  // Helper for adding text with auto-wrapping
  const addText = (text: string, fontSize: number, isBold: boolean = false) => {
    doc.setFontSize(fontSize);
    doc.setFont("helvetica", isBold ? "bold" : "normal");
    
    // Calculate lines
    const splitText = doc.splitTextToSize(text, contentWidth);
    const lineHeight = fontSize * 0.5; // Approximation for spacing
    const blockHeight = splitText.length * lineHeight;

    // Check for page break
    if (yPos + blockHeight > doc.internal.pageSize.getHeight() - margin) {
      doc.addPage();
      yPos = margin;
    }
    
    doc.text(splitText, margin, yPos);
    yPos += blockHeight + (fontSize * 0.3); // Add some spacing after block
  };

  // Title
  addText(data.title, 22, true);
  yPos += 5;
  
  // Metadata
  addText(`Date: ${data.date || new Date().toLocaleDateString()}`, 10);
  addText(`Language: ${data.language}`, 10);
  
  if (data.attendees && data.attendees.length > 0) {
    addText(`Attendees: ${data.attendees.join(', ')}`, 10);
  }
  yPos += 10;

  // Executive Summary
  addText("Executive Summary", 14, true);
  addText(data.executiveSummary, 11);
  yPos += 5;

  // Narrative Sections
  if (data.narrativeSections && data.narrativeSections.length > 0) {
    data.narrativeSections.forEach(section => {
      addText(section.title, 12, true);
      addText(section.content, 11);
      yPos += 3;
    });
    yPos += 5;
  }

  // Key Points
  if (data.keyPoints && data.keyPoints.length > 0) {
    addText("Key Discussion Points", 14, true);
    data.keyPoints.forEach(point => {
      addText(`• ${point}`, 11);
    });
    yPos += 5;
  }

  // Decisions Made
  if (data.decisionsMade && data.decisionsMade.length > 0) {
    addText("Decisions Made", 14, true);
    data.decisionsMade.forEach(decision => {
      addText(`• ${decision}`, 11);
    });
    yPos += 5;
  }

  // Action Items
  if (data.actionItems && data.actionItems.length > 0) {
    addText("Action Items", 14, true);
    data.actionItems.forEach(item => {
      const text = `[ ] ${item.task} (Assignee: ${item.assignee}, Priority: ${item.priority})`;
      addText(text, 11);
    });
  }

  // Footer
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text("Generated by MindRecap AI", margin, pageHeight - 10);

  doc.save(`${data.title.replace(/\s+/g, '_')}_Notes.pdf`);
};

export const generateWord = (data: MeetingAnalysis) => {
  const doc = new Document({
    sections: [
      {
        properties: {},
        children: [
          new Paragraph({
            text: data.title,
            heading: HeadingLevel.TITLE,
            alignment: AlignmentType.CENTER,
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: `Date: ${data.date || new Date().toLocaleDateString()}`,
                bold: true,
              }),
              new TextRun({
                text: `\nLanguage: ${data.language}`,
                break: 1,
              }),
              new TextRun({
                text: `\nAttendees: ${data.attendees?.join(', ') || 'None listed'}`,
                break: 1,
              }),
            ],
            spacing: { after: 200 },
          }),
          
          new Paragraph({
            text: "Executive Summary",
            heading: HeadingLevel.HEADING_1,
          }),
          new Paragraph({
            text: data.executiveSummary,
            spacing: { after: 200 },
          }),

          ...(data.narrativeSections || []).flatMap(section => [
            new Paragraph({
              text: section.title,
              heading: HeadingLevel.HEADING_2,
              spacing: { before: 200, after: 100 },
            }),
            new Paragraph({
              text: section.content,
              spacing: { after: 200 },
            }),
          ]),

          new Paragraph({
            text: "Key Discussion Points",
            heading: HeadingLevel.HEADING_1,
            spacing: { before: 200 },
          }),
          ...(data.keyPoints || []).map(point => 
            new Paragraph({
              text: point,
              bullet: { level: 0 },
            })
          ),

          new Paragraph({
            text: "Decisions Made",
            heading: HeadingLevel.HEADING_1,
            spacing: { before: 200 },
          }),
          ...(data.decisionsMade || []).map(decision => 
            new Paragraph({
              text: decision,
              bullet: { level: 0 },
            })
          ),

          new Paragraph({
            text: "Action Items",
            heading: HeadingLevel.HEADING_1,
            spacing: { before: 200 },
          }),
          ...(data.actionItems || []).map(item => 
            new Paragraph({
              children: [
                new TextRun({
                  text: `[ ] ${item.task}`,
                  bold: true,
                }),
                new TextRun({
                  text: ` (Assignee: ${item.assignee}, Priority: ${item.priority})`,
                  italics: true,
                }),
              ],
              bullet: { level: 0 },
            })
          ),
          
          new Paragraph({
            text: "Generated by MindRecap AI",
            alignment: AlignmentType.CENTER,
            spacing: { before: 400 },
            children: [
              new TextRun({
                text: "Generated by MindRecap AI",
                size: 16,
                color: "888888",
              }),
            ],
          }),
        ],
      },
    ],
  });

  Packer.toBlob(doc).then((blob) => {
    saveAs(blob, `${data.title.replace(/\s+/g, '_')}_Notes.docx`);
  });
};
